---
output: 
  html_document:
    theme: paper
    highlight: kate
---

#### Team Aga
- - -

#### Task 1

```{r}
if('pacman' %in% rownames(installed.packages()) == FALSE) {
  install.packages('pacman', repos = "http://cran.case.edu")
}
pacman::p_load(gdata, rjags, rnoaa, ecoforecastR, MCMCvis)
knitr::opts_chunk$set(cache = TRUE)
```

Use the Google Flu Trends data for the state of Massachusetts.

```{r, fig.align = 'center'}
work1 = read.xls("../TeamAga/Mariana_Crow_MARK.xlsx", sheet = 1)
f <- rep(0, dim(work1)[1])

for(i in 1:dim(work1)[1]) {
  for (j in 3:18) {
    if (work1[i, j]==1 & f[i]==0) f[i] <- j - 2
  }
}

f <- f[f>0]
work2 <- work1[which(f>0), ]
nind <- dim(work2)[1]
nyears <- 18 - 3 + 1
y <- as.matrix(work2[, 3:18])
total <- apply(y, 2, sum)
data = list(y = y, nind = nind, nyears = nyears, f = f, total = total)
    ```

JAGS code for the cormack jolly seber model.

```{r}
CJS = "

model {

# Priors and constraints
for (i in 1:nind) {
  for (t in f[i]:(nyears - 1)) {
    phi[i, t] <- mean.phi
    p[i, t] <- mean.p
  } #t
} #i

mean.phi ~ dunif(0, 1)
mean.p ~ dunif(0, 1) 

# Likelihood 

for (i in 1:nind) {
  # Define latent state at first capture
  z[i,f[i]] <- 1
  for (t in (f[i] + 1):nyears) {
    z[i, t] ~ dbern(mu1[i, t])
    mu1[i, t] <- phi[i, t-1] * z[i, t-1]
    y[i, t] ~ dbern(mu2[i, t])
    mu2[i, t] <- p[i, t-1] * z[i, t]
  } #t
} #i

for (i in 2:nyears) {
  n[i] <- total[i] / mean.p 
}

}
"
```

```{r}
rinits <- function() {
  z <- matrix(NA, nrow = nind, ncol = nyears)
  for (i in 1:nind) {
    for(j in 1:nyears) {
      if (j > f[i]) z[i, j] <- 1
    }
  }
  mean.phi <- runif(1, .4, .6)
  mean.p <- runif(1, .4, .6)
  return(list(z = z, mean.phi = mean.phi, mean.p = mean.p))
}
```

```{r}
params <- c("mean.phi", "mean.p", "n")
jm <- jags.model(file = textConnection(CJS), data = data, inits = rinits(), n.chains = 3, n.adapt = 5000)
update(jm, n.iter = 10000)
samples = coda.samples(jm, n.iter = 20000, variable.names = params, thin = 2)
```

```{r, fig.align = 'center'}
MCMCvis::MCMCsummary(samples, params = c("mean.phi", "mean.p"), n.eff = TRUE)
MCMCvis::MCMCtrace(samples, params = c("mean.phi", "mean.p"), pdf = F)
```

```{r, fig.align = 'center'}
n <- apply(MCMCvis::MCMCchains(samples, params = "n"), 2, quantile, probs = c(.025, .5, .975))
years <- seq(1999, 2013)
plot(range(1999, 2013), range(0, 120), type = 'n', xlab = 'year', ylab = 'adult crows')
ecoforecastR::ciEnvelope(years, n[1, ], n[3, ], col = "lightBlue")
lines(years, n[2, ], lwd = 1, col = "blue", lty = 1, type = 'l')
points(years, n[2, ], pch = 16, cex = 1.2)
```


